master:
  image: mesosphere/mesos:1.0.0
  command: mesos-master --work_dir=/mesos
  ports:
    - 5050:5050

slave:
  image: mesosphere/mesos:1.0.0
  links:
    - master:master
  command: mesos-slave --work_dir=/mesos --master=master:5050 --containerizers=docker,mesos
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/bin/docker

swan:
   build: .
   links:
    - master:master
   command: --masters=master:5050
   ports:
     - 9999:9999
